CREATE DATABASE IF NOT EXISTS jeu_de_mots;
USE jeu_de_mots;

CREATE TABLE IF NOT EXISTS joueurs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    mot_de_passe VARCHAR(255) NOT NULL,
    points INT DEFAULT 0
);
